using Microsoft.EntityFrameworkCore.Migrations;
using NetTopologySuite.Geometries;

#nullable disable

namespace AccesUrbanMap.Infrastructure.Persistence.Migrations;

/// <summary>
/// Restores real PostGIS support and connects the existing error_logs table to EF.
/// </summary>
public partial class AddPostgisAndErrorLogging : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterDatabase()
            .Annotation("Npgsql:PostgresExtension:postgis", ",,");

        migrationBuilder.AddColumn<Point>(
            name: "geometry",
            table: "reports",
            type: "geometry(Point,4326)",
            nullable: true);

        migrationBuilder.AddColumn<Point>(
            name: "geometry",
            table: "places",
            type: "geometry(Point,4326)",
            nullable: true);

        migrationBuilder.Sql(@"
            UPDATE places
            SET geometry = ST_SetSRID(
                ST_MakePoint(longitude::double precision, latitude::double precision),
                4326)
            WHERE geometry IS NULL;

            UPDATE reports
            SET geometry = ST_SetSRID(
                ST_MakePoint(longitude::double precision, latitude::double precision),
                4326)
            WHERE geometry IS NULL AND latitude IS NOT NULL AND longitude IS NOT NULL;");

        migrationBuilder.AlterColumn<Point>(
            name: "geometry",
            table: "places",
            type: "geometry(Point,4326)",
            nullable: false,
            oldClrType: typeof(Point),
            oldType: "geometry(Point,4326)",
            oldNullable: true);

        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS error_logs
            (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                trace_id varchar(128) NOT NULL,
                user_id integer NULL,
                request_method varchar(16) NOT NULL,
                request_path varchar(2048) NOT NULL,
                status_code integer NOT NULL,
                exception_type varchar(512) NOT NULL,
                message varchar(4000) NOT NULL,
                stack_trace text NULL,
                created_at timestamp with time zone NOT NULL,
                user_email varchar(320) NULL,
                user_name varchar(160) NULL
            );

            ");

        migrationBuilder.Sql(
            "CREATE INDEX IF NOT EXISTS \"IX_places_geometry\" ON places USING GIST (geometry);");
        migrationBuilder.Sql(
            "CREATE INDEX IF NOT EXISTS \"IX_error_logs_created_at\" ON error_logs (created_at);");
        migrationBuilder.Sql(
            "CREATE INDEX IF NOT EXISTS \"IX_error_logs_trace_id\" ON error_logs (trace_id);");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_error_logs_trace_id\";");
        migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_error_logs_created_at\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS error_logs;");
        migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_places_geometry\";");
        migrationBuilder.DropColumn(name: "geometry", table: "reports");
        migrationBuilder.DropColumn(name: "geometry", table: "places");

        migrationBuilder.AlterDatabase()
            .OldAnnotation("Npgsql:PostgresExtension:postgis", ",,");
    }
}
