/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ContacteRouteImport } from './app/routes/contacte'
import { Route as HomeRouteImport } from './app/routes/home'
import { Route as MapRouteImport } from './app/routes/map'
import { Route as ProgrameRouteImport } from './app/routes/programe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContacteRoute = ContacteRouteImport.update({
  id: '/contacte',
  path: '/contacte',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrameRoute = ProgrameRouteImport.update({
  id: '/programe',
  path: '/programe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacte': typeof ContacteRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/programe': typeof ProgrameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacte': typeof ContacteRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/programe': typeof ProgrameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacte': typeof ContacteRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/programe': typeof ProgrameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacte' | '/home' | '/map' | '/programe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacte' | '/home' | '/map' | '/programe'
  id: '__root__' | '/' | '/contacte' | '/home' | '/map' | '/programe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContacteRoute: typeof ContacteRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  ProgrameRoute: typeof ProgrameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacte': {
      id: '/contacte'
      path: '/contacte'
      fullPath: '/contacte'
      preLoaderRoute: typeof ContacteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programe': {
      id: '/programe'
      path: '/programe'
      fullPath: '/programe'
      preLoaderRoute: typeof ProgrameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContacteRoute: ContacteRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  ProgrameRoute: ProgrameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
